//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISomeCoolService")]
    public interface ISomeCoolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeCoolService/DoSomethingRealCool", ReplyAction="http://tempuri.org/ISomeCoolService/DoSomethingRealCoolResponse")]
        string DoSomethingRealCool(string someArg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeCoolService/DoSomethingRealCool", ReplyAction="http://tempuri.org/ISomeCoolService/DoSomethingRealCoolResponse")]
        System.Threading.Tasks.Task<string> DoSomethingRealCoolAsync(string someArg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISomeCoolServiceChannel : SoapClient.ServiceReference1.ISomeCoolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomeCoolServiceClient : System.ServiceModel.ClientBase<SoapClient.ServiceReference1.ISomeCoolService>, SoapClient.ServiceReference1.ISomeCoolService {
        
        public SomeCoolServiceClient() {
        }
        
        public SomeCoolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SomeCoolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeCoolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomeCoolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoSomethingRealCool(string someArg) {
            return base.Channel.DoSomethingRealCool(someArg);
        }
        
        public System.Threading.Tasks.Task<string> DoSomethingRealCoolAsync(string someArg) {
            return base.Channel.DoSomethingRealCoolAsync(someArg);
        }
    }
}
